spring:
  application:
    name: transaction-service
  datasource:
    url: ${DB_URL_TRANSACTION}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type: true
  config:
    import: optional:file:.env[.properties]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: ${JWT_SECRET}
